Dev docs
pola-rs/r-polars pull request #123
Opened 2023-04-17 23:29 UTC by grantmcdermott

Closes #85. (At least, it should do.)

I also fixed a typo in the README and added a minor section on R-universe for Ubuntu 22.04.

2023-04-18 00:08 UTC, eddelbuettel commented
There is paralle change about r-universe in #122 so let's maybe easier to do them one a time and then rebase this one?

2023-04-18 00:21 UTC, grantmcdermott commented
Sgtm

2023-04-18 10:49 UTC, eitsupi requested changes
I think the workflow needs to be updated too.

https://github.com/pola-rs/r-polars/blob/204dd2d456d7895373e159603aa7fdfbc6569202/.github/workflows/pkgdown.yaml#L105-L106

2023-04-18 12:51 UTC, eddelbuettel commented on README.Rmd
> +[![Docs dev](https://img.shields.io/badge/docs-dev-blue.svg)](https://rpolars.github.io/dev)
(Style nit)   How about     'Docs (release)'  and 'Docs (devel)'   ?

2023-04-18 12:52 UTC, eddelbuettel commented on README.Rmd
> +)
(Style nit, personal)  I really do not like that indentation.  The original single line 59 is so much easier to read, grasp and copy than new four lines 59 to 62.

2023-04-18 12:55 UTC, eddelbuettel reviewed
I added some comments inline.

2023-04-18 16:18 UTC, eitsupi commented on README.Rmd
> +)
I am +1 to removing this and (r2u's one).
As you know, this will be outdated in a week.

2023-04-18 16:46 UTC, eddelbuettel commented on README.Rmd
> +)
_Au contraire_ we then switch to 4.3.  Jammy remains LTS for another year.

2023-04-18 16:54 UTC, grantmcdermott commented
> I think the workflow needs to be updated too.
> 
> https://github.com/pola-rs/r-polars/blob/204dd2d456d7895373e159603aa7fdfbc6569202/.github/workflows/pkgdown.yaml#L105-L106

Ah, my bad. Will update now. One thing I noticed is that you deploy off the `main` branch rather than `gh-pages` ([line 110](https://github.com/pola-rs/r-polars/blob/main/.github/workflows/pkgdown.yaml#L110)). Is there a reason for this?

2023-04-18 16:59 UTC, grantmcdermott commented on README.Rmd
> +)
Tell you what: I'll remove this change and let you figure out the current r2u section on the backend.

Two quick takes in passing: 1) I think it's easy enough to update the endpoint manually to 4.3 in a week. So it doesn't hurt to keep it somewhere. 2) Much as a I love r2u, I don't think it supersedes a "pure" r-universe option for this README. The real appeal is getting arrow for free too, but's getting a bit off spec. So if you were to keep one, I'd opt for r-universe only (but maybe with r2u as a footnote).

2023-04-18 23:24 UTC, eitsupi approved these changes

2023-04-18 23:26 UTC, eitsupi commented
@grantmcdermott Sorry, my point was to change the conditions that trigger a deploy.

2023-04-19 00:49 UTC, sorhawell approved these changes

2023-04-19 00:50 UTC, sorhawell commented
Many thanks @grantmcdermott 

Looking forward to see this in action :)

2023-04-19 00:51 UTC, merged

2023-05-01 05:49 UTC, eitsupi commented on README.Rmd
> +)
Could you update this as R-universe has switched to R 4.3?
If someone other than me does not maintain this section, I am +1 to remove these lines about Ubuntu binary installation in R-universe (and about r2u).

Binaries that can be installed from R-universe have SIMD disabled and may be less functional than the GitHub release or the source installation.