WIP: melt + pivot
pola-rs/r-polars pull request #232
Opened 2023-06-03 22:31 UTC by sorhawell

solves #231

2023-06-03 22:31 UTC, sorhawell commented
DataFrame.pivot + DataFrame.melt + tests still missing

2023-06-06 15:28 UTC, eitsupi requested changes

2023-06-06 15:28 UTC, eitsupi commented on tests/testthat/_snaps/knitr.new.md
It seems that unnecessary file has been added.

2023-06-06 16:04 UTC, sorhawell commented on tests/testthat/_snaps/knitr.new.md
Oh, thanks :)

2023-06-07 11:10 UTC, eitsupi approved these changes
Thanks!

2023-06-07 11:10 UTC, merged