Implement string method `to_titlecase()`
pola-rs/r-polars pull request #373
Opened 2023-09-05 16:45 UTC by etiennebacher

2023-09-05 20:17 UTC, etiennebacher commented
This only succeeds with full-features enabled, maybe because this function is marked as `nightly`?

https://github.com/pola-rs/polars/blob/0d90a06536804e7c041d72a244f0dcb4e104c66b/crates/polars-plan/src/dsl/string.rs#L488

2023-09-05 21:37 UTC, sorhawell commented
Uhh have seen such method that before relying on nightly I think.
I added some conditional compilation. Now `$to_titlecase()`will throw an error if not compiled with "full_feaures" aka envvar "RPOLARS_FULL_FEATURES". There is a function to check on R side if full features also `polars:::polars_has_full_feaures()`

2023-09-05 22:07 UTC, eitsupi requested changes

2023-09-05 22:07 UTC, eitsupi commented on src/rust/src/rlib.rs
> +}
How about use the `!cfg` macro?

2023-09-05 22:07 UTC, eitsupi commented on src/rust/src/lazy/dsl.rs
> +}
Can't we evaluate the feature flag in the function?

2023-09-06 06:19 UTC, etiennebacher reviewed
thanks for fixing it @sorhawell, I have a comment about `polars_features()`

2023-09-06 06:19 UTC, etiennebacher commented on R/extendr-wrappers.R
> +polars_features <- function() .Call(wrap__polars_features)
This is a bit a duplicate of `polars::pl$polars_info()`, is it possible to merge the two?
```r
polars::pl$polars_info()
#> r-polars package version : 0.8.0.9000
#> rust-polars crate version: 0.32.0
#> 
#> Features:          
#> simd FALSE

polars_features()
#> $full_features
#> [1] FALSE
#> 
#> $default
#> [1] TRUE
#> 
#> $simd
#> [1] FALSE
#> 
#> $rpolars_debug_print
#> [1] FALSE
```

2023-09-06 10:47 UTC, eitsupi approved these changes
Looks good, thanks!

2023-09-06 10:47 UTC, eitsupi commented on NEWS.md
> +
```suggestion
```

2023-09-06 10:47 UTC, eitsupi commented on tests/testthat/test-expr_string.R
> +
```suggestion
```

2023-09-06 10:47 UTC, eitsupi commented on tests/testthat/test-expr_string.R
> +
```suggestion
```

2023-09-06 11:25 UTC, merged

2023-12-03 04:32 UTC, eitsupi commented on src/rust/src/rlib.rs
> +}
This seems unused.