refactor scan/read_parquet + support more args
pola-rs/r-polars pull request #492
Opened 2023-11-09 22:46 UTC by sorhawell

2023-11-09 22:52 UTC, eitsupi requested changes

2023-11-09 22:52 UTC, eitsupi commented on R/parquet.R
> +  mc[[1]] = pl$scan_parquet
```suggestion
  mc[[1]] = get("pl", envir = asNamespace("polars"))$scan_parquet
```

If we do not do this, it seems that an error will occur if we use the package without loading it like `polars::pl$read_parquet("foo.parquet")`.

2023-11-12 23:26 UTC, sorhawell commented
@eitsupi  sorry for circling around the match.call eval.

I noticed in new utest `"scan read parquet from other process"` that`eval.parent` and not `eval` is needed to scope some args. But using eval.parent makes the frame stack a bit strange, and parent frame could very well be ´R_GlobalEnv´. Maybe that could give some unexpected behavior one day.

How about `do.call(f, args)`?
```R

pl$read_parquet(x,y,z) { 
  args = as.list(environment())
    result({
      do.call(pl$scan_parquet, args)$collect()
    }) |>
      unwrap("in pl$read_parquet(): ")
  }
```

2023-11-13 08:00 UTC, etiennebacher commented
> How about do.call(f, args)?

This looks more robust indeed

2023-11-13 10:22 UTC, eitsupi commented
> How about `do.call(f, args)`?

Actually I am not familiar with these but they seem to work well, thanks!

2023-11-13 10:23 UTC, eitsupi approved these changes

2023-11-13 12:20 UTC, etiennebacher commented on tests/testthat/test-parquet.R
> +})
can you split these tests into several `test_that()` calls?

2023-11-15 06:21 UTC, etiennebacher commented
Thanks! I'll just tweak a few things before merging

2023-11-15 06:54 UTC, merged