rpolars_style + utils
pola-rs/r-polars pull request #594
Opened 2023-12-11 21:35 UTC by sorhawell

2023-12-12 13:48 UTC, eitsupi requested changes
Thanks for working on this!
I'm sorry, but I'm on a business trip and can't see this in detail for a while.

For the time being, since the tools directory is for storing files that are used when installing R packages, could you please move this to the dev directory?

2023-12-15 14:09 UTC, sorhawell commented
I will try to incorporate this in the current Makefile as a suggestion of how it could be used. I know there might be an upcoming Tasks file to use instead

2023-12-15 18:47 UTC, sorhawell commented
besides running like this to style changes, it takes 1-8 seconds
```sh
make fmt-r
```

sometimes every .e.g. .R file could be styled something like like this, it would probably take 1-2 min
```R
source("dev/styler_utils.R")
style_files(list.files(".",full.names=TRUE, pattern = "*.R$"))
```

or using the styler package directly. This could take 2-10 min
```R
source("dev/styler_utils.R")
styler::style_pkg(".", style = rpolars_style)
```

2023-12-15 20:19 UTC, sorhawell commented
@eitsupi  I don't know why but it seems check is disabled for some reasone

Styling is now fairly verbose, we can set `verbose = FALSE`

2023-12-16 00:49 UTC, sorhawell commented on dev/styler_utils.R
> +    Sys.setenv("GIT_DIF_TARGET" = "main")
Should touch GIT_DIF_TARGET if branch is NULL

2023-12-17 06:51 UTC, eitsupi approved these changes
Seems working fine, thanks!

2023-12-17 06:52 UTC, merged

2023-12-17 11:26 UTC, eitsupi commented
@sorhawell If we use this, it seems that `<<-` will be changed to `=`. Could you fix it?

2023-12-18 15:02 UTC, eitsupi commented
@sorhawell Could you fix this?