rpolars_style 0.1.1: fix styler `<<-`   and style all files
pola-rs/r-polars pull request #608
Opened 2023-12-18 16:35 UTC by sorhawell

update to rpolars_style  to not convert  the `<<-`  operator to `=` in e.g. `utils.R`

2023-12-18 16:43 UTC, sorhawell commented
follow up to #594

2023-12-18 16:46 UTC, sorhawell commented
styled all files with this

```R
source("dev/styler_utils.R")
style_files(list.files(".",full.names=TRUE, pattern = "\\.R$|\\.Rmd$", recursive = TRUE))
```

2023-12-18 22:47 UTC, eitsupi requested changes

2023-12-18 22:47 UTC, eitsupi commented on R/extendr-wrappers.R
This file should not be updated.

2023-12-19 14:26 UTC, sorhawell commented on R/extendr-wrappers.R
reverted file, and added function `style_entire_pkg()`

```R
style_entire_pkg = function() {
  list.files(".", full.names = TRUE, pattern = "\\.R$|\\.Rmd$", recursive = TRUE) |>
    setdiff("./R/extendr-wrappers.R") |>
    style_files()
}
```

2023-12-19 15:09 UTC, eitsupi approved these changes
Thanks, let's try merging.

2023-12-19 20:18 UTC, sorhawell commented
for reference added function to style all files 
```R
source("dev/styler_utils.R")
style_entire_pkg()
```

instead of just styling files of a given PR
```R
style_files()
```

2023-12-19 20:19 UTC, merged