build: add Taskfile.yml to use task as a build tool
pola-rs/r-polars pull request #617
Opened 2023-12-23 15:41 UTC by eitsupi

2023-12-23 15:47 UTC, eitsupi commented
At the moment, only the main targets have been ported from the Makefile, and the minor targets have not yet been ported.
But building and testing the entire package should work. Like `task build-all`, `task build-website`, etc.

@etiennebacher Could you try this?
Task should work on Windows since it doesn't depend on Unix shell, but I haven't tested it here.

2023-12-23 16:27 UTC, etiennebacher commented
Thanks @eitsupi, I confirm it works fine on Windows once I downloaded `Task` (I just tried `build-all` and `setup-dev`). I'll need more time to see if it fixes #613 but at least the basic usage works

2023-12-24 00:49 UTC, eitsupi commented on Taskfile.yml
> +      - vignettes/*.Rmd
We can use the `{{.VIGNETTES}}` variable instead of this.

2023-12-24 14:50 UTC, eitsupi commented
I believe I have ported the full functionality of the Makefile.

```sh
task setup-dev
task build-all
task build-website
```

2023-12-24 16:34 UTC, etiennebacher requested changes
I think the documentation workflow needs to be updated as well to use task instead

2023-12-24 23:19 UTC, eitsupi commented
> I think the documentation workflow needs to be updated as well to use task instead

I'd like to do that in a follow-up PR. This PR includes an update to Rbuildignore, so it triggers the R workflow needlessly.

2023-12-25 06:19 UTC, etiennebacher approved these changes
Thanks @eitsupi

2023-12-25 10:09 UTC, eitsupi commented
Thanks for taking a look at this.

2023-12-25 10:09 UTC, merged

2024-01-01 13:13 UTC, etiennebacher commented
@eitsupi I use the taskfile more regularly now and the Rust crates are only compiled once with `task build-all`, thanks!