Fix absence of "Usage" section for Expr subnamespaces
pola-rs/r-polars pull request #642
Opened 2024-01-01 15:14 UTC by etiennebacher

None of the Expr subnamespaces (DT, list, etc.) have a "Usage" section in the docs. This is because the internal function `macro_new_subnamespace()` is run before the Rd files are generated by `roxygen`.  The problem is that `macro_new_subnamespace()` removes the functions that are defined (e.g `ExprDT_days()`) and renames them, so when `roxygen` tries to detect how to use `ExprDT_days()`, it doesn't exist anymore and therefore the usage section is empty. This is also why we need to manually add the `@name` tag.

This PR fixes this by removing the argument `remove_f` in `macro_new_subnamespace()`, which means that the original functions are no longer deleted. I don't think this has an effect on the users: the snapshots that list all methods are not modified and all the tests pass.

In a follow-up PR, I'll deal with renaming the `ExprDT_` into something cleaner on the website (something similar to #626).

2024-01-01 16:13 UTC, etiennebacher commented on R/utils.R
This is the main change

2024-01-01 16:14 UTC, etiennebacher commented on R/utils.R
> +macro_new_subnamespace = function(class_pattern, subclass_env = NULL) {
This is the main change

2024-01-02 01:28 UTC, eitsupi requested changes
Thanks for working on this!

2024-01-02 01:28 UTC, eitsupi commented on man/S3_knit_print.Rd
Unnecessary change.

2024-01-02 01:28 UTC, eitsupi commented on man/nanoarrow.Rd
Ditto.

2024-01-02 10:17 UTC, eitsupi approved these changes

2024-01-02 10:17 UTC, merged