Implement `group_by_dynamic()` for `DataFrame` and `LazyFrame`
pola-rs/r-polars pull request #691
Opened 2024-01-11 12:54 UTC by etiennebacher

2024-01-11 19:10 UTC, etiennebacher commented on tests/testthat/test-groupby.R
> +
I only moved this above because otherwise RStudio doesn't provide the button "Test"

2024-01-12 14:40 UTC, eitsupi commented on R/group_by.R
Why not completely rewrite GroupBy first? https://github.com/pola-rs/r-polars/pull/682#pullrequestreview-1812880011

2024-01-13 16:16 UTC, etiennebacher commented
@eitsupi I ended up removing the attributes when we print the `DynamicGroupBy` and `RollingGroupBy` objects because if we print this class of objects, it means they are last in the pipeline, so we already have all the info about groups and other args. Maybe that's what you said in #694, I'm not sure.

2024-01-14 03:59 UTC, eitsupi requested changes

2024-01-14 03:59 UTC, eitsupi commented on R/lazyframe__lazy.R
> +    check_sorted = TRUE) {
(as well as other functions) Could you please enforce named arguments using `...`?
https://github.com/pola-rs/polars/blob/cdef09b98f5164271ac1a489b395accf4a363549/py-polars/polars/lazyframe/frame.py#L3113-L3127

2024-01-14 04:34 UTC, eitsupi approved these changes
Thanks!

2024-01-14 07:53 UTC, merged