refactor: remove `data.table` from suggests
pola-rs/r-polars pull request #849
Opened 2024-02-25 06:51 UTC by eitsupi

In fact, it is used only within the tests and there is little need to use it.

2024-02-25 07:55 UTC, etiennebacher requested changes
I'm ok to remove it but the examples that are removed should be replaced with a base R alternative. I see only one remaining test for `$melt()` and that's not enough for this functionality

2024-02-26 14:49 UTC, eitsupi commented
Thanks for your review.
I rewrote tests for `$melt()`.

2024-02-26 17:22 UTC, etiennebacher requested changes

2024-02-26 17:22 UTC, etiennebacher commented on tests/testthat/test-melt.R
> +    )
This is identical to `df_1`?

2024-02-26 17:22 UTC, etiennebacher commented on tests/testthat/test-melt.R
> +    expect_error
missing something here

2024-02-27 07:20 UTC, etiennebacher approved these changes
Thanks, LGTM

2024-02-27 07:20 UTC, merged