[WIP] fix!: change the default delimiter of `$str$concat` from `"-"` to `""`
pola-rs/r-polars pull request #853
Opened 2024-02-26 13:59 UTC by eitsupi

Ref pola-rs/polars#13690

2024-02-27 18:26 UTC, etiennebacher requested changes

2024-02-27 18:26 UTC, etiennebacher commented on R/expr__string.R
>  #' @keywords ExprStr
```suggestion
```

2024-02-27 18:26 UTC, etiennebacher commented on R/expr__string.R
> +#' )
this should probably be an example for `list$eval()` instead?

2024-02-28 10:38 UTC, eitsupi commented on NEWS.md
> +        changed from `"-"` to `""` (#853).
I would like to change now as it is too much of a hassle to split the update into two separate updates.

2024-02-28 12:08 UTC, etiennebacher approved these changes
Thanks!

2024-02-28 12:08 UTC, merged