fix: pass `join_nulls` and `validate` to the lazy method for `$join()$`
pola-rs/r-polars pull request #949
Opened 2024-03-19 18:10 UTC by george-wood

2024-03-19 21:35 UTC, etiennebacher reviewed
Thanks @george-wood, that looks good to me. Can you also add tests for the arg 
`validate` for `DataFrame`?

2024-03-20 05:13 UTC, eitsupi commented on R/dataframe__frame.R
I'm wondering if we can use `do.call` instead of specifying all arguments here.
https://github.com/pola-rs/r-polars/blob/b5e0927262cb3823980b768bae5c20bb5e852190/R/io_parquet.R#L97-L100

2024-03-21 10:37 UTC, george-wood commented on R/dataframe__frame.R
Good idea. I've used `do.call` instead. I also added tests for the `validate` arg.

2024-03-21 10:47 UTC, eitsupi requested changes
Could you resolve conflicts of the NEWS file?

2024-03-21 10:53 UTC, eitsupi approved these changes
LGTM, thanks for the contribution!

2024-03-21 10:55 UTC, eitsupi commented on NEWS.md
> +
```suggestion

```

2024-03-21 11:07 UTC, george-wood commented
> LGTM, thanks for the contribution!

Thanks for reviewing!

2024-03-21 11:31 UTC, merged